# Generated by Django 3.2.4 on 2022-10-02 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('primary_list_clickup', models.CharField(blank=True, max_length=256, null=True)),
                ('secondary_list_lickup', models.CharField(blank=True, max_length=256, null=True)),
                ('tertiary_list_lickup', models.CharField(blank=True, max_length=256, null=True)),
                ('token_clickup', models.CharField(blank=True, max_length=256, null=True)),
                ('token_sms', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
