# Generated by Django 3.2.4 on 2022-10-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='clickup_user_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
