# Generated by Django 3.2.4 on 2022-10-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_customer_clickup_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='tertiary_list_lickup',
            new_name='name_second_task',
        ),
    ]
