# Generated by Django 3.2.4 on 2022-10-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_tertiary_list_lickup_customer_name_second_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name_tertiary_task',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tertiary_list_lickup',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
