# Generated by Django 3.2.4 on 2022-10-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_customer_clickup_phone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='clickup_phone_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
