# Generated by Django 3.2.4 on 2022-10-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_customer_clickup_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='clickup_source_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
