# Generated by Django 3.2.4 on 2022-10-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='extended',
        ),
        migrations.AddField(
            model_name='lead',
            name='key_word',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='LeadExtended',
        ),
    ]
