# Generated by Django 3.2.4 on 2022-10-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20221002_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.campaign', to_field='system_ads_id'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='rodo',
            field=models.BooleanField(default=False),
        ),
    ]
