# Generated by Django 3.2.4 on 2022-10-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20221002_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.campaign'),
        ),
    ]
