# Generated by Django 3.2.4 on 2022-10-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_campaign_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='system_ads_id',
        ),
    ]
