# Generated by Django 3.2.4 on 2022-10-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_campaign_system_ads_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
