# Generated by Django 3.2.4 on 2022-10-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_rename_link_lp_campaign_landing_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
