# Generated by Django 3.2.4 on 2022-10-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_landingpage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadExtend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='key_word',
        ),
    ]
