# Generated by Django 3.2.4 on 2022-10-03 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_lead_lead_extend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='landing_page',
        ),
        migrations.AddField(
            model_name='lead',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.landingpage'),
        ),
    ]
