# Generated by Django 3.2.4 on 2022-10-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_remove_campaign_campaign_clickup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sms_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
